# admin =
@jwt_admin = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTgzNzU2MDJ9.-4TH1wvkwUWDsEpAf6L0tANQ_GhR2q_crM4_Z7G8PEo

@jwt_user = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTgzNzU1Njd9.l7VMFRjtsoYoysSQ6QfFPPXo6V4DpMVA2X_AjPbNCJY

### INDEX
GET   http://localhost:3000/actors

### INDEX
GET   http://localhost:3000/movies

### SHOW
GET   http://localhost:3000/actors/10

### UPDATE
PATCH http://localhost:3000/actors/10
Authorization: Bearer {{jwt_admin}}
Content-Type: application/json

{
"last_name": "Musk"
}

### CREATE
POST http://localhost:3000/actors.json
Authorization: Bearer {{jwt_admin}}
Content-Type: application/json

{
  "first_name": "Test name",
  "last_name": "blah blah",
  "known_for": "something"
}
### DESTROY
DELETE http://localhost:3000/actors/28.json
Authorization: Bearer {{jwt_admin}}



### INDEX
GET http://localhost:3000/movies.json

### SHOW
GET http://localhost:3000/movies/5.json

### UPDATE
PATCH http://localhost:3000/movies/10
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
"title": "The Blob"
}

### CREATE
POST http://localhost:3000/movies.json
Authorization: Bearer {{jwt_admin}}
Content-Type: application/json

{
  "title": "Test name",
  "year": 1960,
  "plot": "something"
}
### DESTROY
DELETE http://localhost:3000/movies/35.json
Authorization: Bearer {{jwt_admin}}

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "john",
  "email": "john@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "john@test.com",
  "password": "password"
}

### CREATE
POST http://localhost:3000/movie_genres.json
Authorization: Bearer {{jwt_admin}}
Content-Type: application/json

{
  "movie_id": 10,
  "genre_id": 4
}