GET   http://localhost:3000/find/22
###

POST http://localhost:3000/find/actor/
Content-Type: application/json

{
"last_name": "Cartwright"
}

###

GET http://localhost:3000/movies.json

###
GET http://localhost:3000/movies/5.json